name 'opentable/nsclient'
version '1.1.0'
author 'opentable'
license 'MIT'
summary 'Module that will install the NSClient on windows servers to be able to interact with Nagios and Icinga. It will also manage the list of hosts that the server can communicate with'
project_page 'https://github.com/opentable/puppet-nsclient'
dependency    'puppetlabs/stdlib', '>=3.0.0'
dependency    'opentable/download_file', '0.0.2'
